# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_SAMGEP_dmvnorm_arma', PACKAGE = 'SAMGEP', x, mean, sigma, logd)
}

dmvnrm_arma_old <- function(x, mean, sigma, logd = FALSE) {
    .Call('_SAMGEP_dmvnrm_arma_old', PACKAGE = 'SAMGEP', x, mean, sigma, logd)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_SAMGEP_dmvnrm_arma', PACKAGE = 'SAMGEP', x, mean, sigma, logd)
}

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call('_SAMGEP_dmvnrm_arma_fast', PACKAGE = 'SAMGEP', x, mean, sigma, logd)
}

